### ISSUE TITLE
chroot: /var/empty nonexistent

### ISSUE THREAD

**Issue by 0xErnie** [jdelic/opensmtpd-plusdashfilter#1]
Moin,

I installed opensmtpd on debian jessie. Using the package from jessie-backports or testing I get the folowing errors:

```
Sep 12 12:42:44 tobi smtpd[11373]: info: OpenSMTPD 5.7.3p2 starting
Sep 12 12:42:44 tobi smtpd[11374]: info: startup
Sep 12 12:42:44 tobi smtpd[11381]: warn: pony -> plusdash: imsg_read: Connection reset by peer
Sep 12 12:42:44 tobi smtpd[11381]: fatal: exiting: Connection reset by peer
Sep 12 12:42:44 tobi smtpd[11378]: warn: control -> pony: pipe closed
Sep 12 12:42:44 tobi smtpd[11382]: warn: ca -> pony: pipe closed
Sep 12 12:42:44 tobi smtpd[11374]: warn: parent -> control: pipe closed
Sep 12 12:42:44 tobi smtpd[11380]: warn: scheduler -> control: pipe closed
Sep 12 12:42:44 tobi smtpd[11377]: warn: queue -> control: pipe closed
Sep 12 12:42:44 tobi smtpd[11379]: warn: lka -> control: pipe closed
```

```
Sep 12 12:16:27 tobi smtpd[8704]: info: OpenSMTPD 5.9.2p1 starting
Sep 12 12:16:27 tobi smtpd[8712]: warn: pony -> plusdash: imsg_read: Connection reset by peer
Sep 12 12:16:27 tobi smtpd[8712]: fatal: exiting: Connection reset by peer
Sep 12 12:16:27 tobi smtpd[8713]: warn: ca -> pony: pipe closed
Sep 12 12:16:27 tobi smtpd[8708]: warn: control -> pony: pipe closed
Sep 12 12:16:27 tobi smtpd[8705]: warn: parent -> ca: pipe closed
Sep 12 12:16:27 tobi smtpd[8711]: warn: scheduler -> control: pipe closed
Sep 12 12:16:27 tobi smtpd[8709]: warn: lka -> control: pipe closed
Sep 12 12:16:27 tobi smtpd[8707]: warn: queue -> control: pipe closed
```

Part of my config:

```
filter plusdash filter-plusdash
listen on eth1 port 25 hostname $Hostname tls pki $PKI filter plusdash
```

**Comment by 0xErnie** [comment]
enabled debuggig

> execv: /usr/lib/x86_64-linux-gnu/opensmtpd/filter-filter-plusdash: No such file or directory
> warn: pony -> plusdash: imsg_read: Connection reset by peer

corrected the configuration.

new error:

> warn: filter-api:plusdash chroot: No such file or directory
> fatal: filter-api: exiting
> warn: pony -> plusdash: imsg_read: Connection reset by peer
> fatal: exiting: Connection reset by peer

**Comment by 0xErnie** [comment]
@jdelic What am I doing wrong here? I suppose you have a working setup using this filter, would you like to describe it?

**Comment by jdelic** [comment]
> What am I doing wrong here? I suppose you have a working setup using this filter, would you like to describe it?

@0xErnie honestly... off the top of my head, I have no idea why this doesn't work. Possibly you're running into problems since the version I published on the public repo is linked against `5.7.1` :-/. I haven't yet moved this into production, so I haven't pushed out any updated builds (https://github.com/OpenSMTPD/OpenSMTPD/issues/659 looks similar to your logs btw).

**Comment by jdelic** [comment]
@0xErnie I finally managed to get some time to look into this some more and I saw the same issue. Can you verify that `/var/empty` exists on the machine your working on?

**Comment by 0xErnie** [comment]
Thank you!
/var/empty did not exist, instead "/var/lib/opensmtpd/empty" is the home directory of opensmtp{d,q}.
I created it and now everything seems to be fine.
